version: "3"
services:
  api:
    build: ./docker/php
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./libra:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: libra
      MYSQL_USER: librauser
      MYSQL_PASSWORD: librapass
      MYSQL_ROOT_PASSWORD: libraroot
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
