<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use App\User;

class ApiControllerTest extends TestCase
{
    use RefreshDatabase;

    protected $user;
    protected $token;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        // テストユーザ作成
        $this->user = factory(User::class)->create();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testLogin()
    {

        $response = $this->json('POST', '/api/login', [
            "email" => $this->user->email,
            "password" => "password",
        ]);
        $this->token = $response["access_token"];

        $response->assertStatus(200);
    }

    /**
     * 認証ユーザー返却テスト
     *
     * @return void
     */
    public function testMe()
    {
        // actingAsヘルパで現在認証済みのユーザーを指定
        $response = $this->actingAs($this->user);
        $response->assertAuthenticated();
        $response->json('GET', '/api/me', [], [
            "accept" => "application/json",
            "Authorization" => "Bearer" . $this->token,
        ]);
        $response->assertPostConditions();
    }
}
